# Generated by Django 5.1.6 on 2025-02-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todos',
        ),
    ]
